### ISSUE TITLE
Regular Expression '^[^|]+\|(?<shortAccession>[^|]+)' does NOT match

### ISSUE THREAD

**Issue by pezhmansafdari** [groupschoof/AHRD#15]
Hi,
I am trying to run AHRD in GO mode and I keep receiving the following error:

WARNING: Regular Expression '^[^|]+\|(?<shortAccession>[^|]+)' does NOT match - using pattern.find(...) - Blast Hit Accession 'Q8M985' - continuing with the original accession. This might lead to unrecognized reference GO annotations!
I have downloaded the GO DB from UniProt and done blastp version 6. 
Would you please let me know what is the problem?
BR,
Pezhman

**Comment by pezhmansafdari** [comment]
Hi,
I have found the source of the problem. I have the:
A0A1S3YUK8
in the second column of my BLAST file instead of :
tr|A0A177VA33|A0A177VA33_9BASI
Is there any way that I can correct for this?
BR,
Pezhman

**Comment by lucventurini** [comment]
Hi @pezhmansafdari, did you by any chance modify the downloaded uniprot file, by e.g. parsing with a script? That could explain the error, and if that is the case, you could just rerun the BLAST.

Otherwise, a quite simple (but involved) solution would be to correct the BLAST file by substituting the values in the second column with the correct values from the original UniProt file. Unfortunately, you would have to write such a script yourself, I doubt there would be an off-the-shelf utility for it.

**Comment by pezhmansafdari** [comment]
Hi, 
I realized this is because I had used –parse_seqids in creating the blast db. So, it is possible to get the IDs only in the second column. Plus, when I try to create a DB without the –parse_seqids option for the whole UniProt db, it throws duplicated seqids error.
